# Default values for batchjobchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#replicaCount: 1

## Job Image
image:
  repository: cekangaki8/simplebatchjob
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.1"

## Job configurations
backoffLimit: 4
restartPolicy: Never
autoCleanupInSeconds: 60
applicationName: simplebatchjob